### ISSUE TITLE
Add a way to create base recipes and import them

### ISSUE THREAD

**Issue by vv9k** [wojciechkepka/pkger#88]
#### Describe your feature request

This feature would allow creating a base recipe that has all common fields shared across many packages and reduce code duplication. For example, packaging python and creating `python-38`, `python-39`, `python-310` packages would only require a base recipe `python` and would only override fields like version and name.

Base recipe `<recipes_dir>/python/recipe.yml`:
```yaml
metadata:
  name: python
  description: '...'
  maintainer: 'Name Surname <Name.Surname@email.com>'
  ...
build:
  ...
```
Child recipe `<recipes_dir>/python-39/recipe.yml`:
```yaml
from: python
metadata:
  name: python-39
  version: 3.9.6
```
Child recipe `<recipes_dir>/python-38/recipe.yml`:
```yaml
from: python
metadata:
  name: python-38
  version: 3.8.2
```

All child recipes share not specified fields with the base recipe `python` specified in `from:`
