### ISSUE TITLE
pkger-deb/pkger-rpm does not work as wildcard for custom images in depends and build-depends recipe params (and probably others)

### ISSUE THREAD

**Issue by lukasz-e** [wojciechkepka/pkger#92]
Documentation states builds for custom images should also use "per-image" options from 'pkger-rpm' or 'pkger-deb' for recipe params like `build`, `build-depends`, `patches`, etc.
But they don't.

### Reproduction steps
Create recipe containing
```
metadata:
  name: test
  ... (other required fields)
  build_depends:
    all: [ ]
    pkger-rpm: [bison]
    pkger-deb: [bison]
  depends:
    all: [gawk]
    pkger-rpm: [bison]
    pkger-deb: [bison]

build:
  steps:
    - cmd: mkdir -p ${PKGER_OUT_DIR}/opt/test && touch ${PKGER_OUT_DIR}/opt/test/a
    - cmd: bison --help
```

Define custom image (in global config and in images) for example as:

```
 - name: rocky8
    target: rpm
    os: Rocky
```
Run build for image rocky8 with `pkger build -i rocky8 -- test`

Build fails with 
```
[ERROR][2022-12-02T21:50:32.996Z][test][7.86.0][rocky8] /bin/sh: bison: command not found
```
(because bison package was not installed during build preparation steps).
When bison package is specified explicitly for `rocky8`, it's properly installed.

The same effect is for debianoids and `pkger-deb` clause.
Simple builds (`-s rpm` / `-s deb`) work properly.

The same problem I observed for `build-depends` recipe option. I did not checked other params that accept per-image values, but  I suspect the problem also occurs for them.

### Environment

- Platform: Ubuntu 20.04, docker 20.10
- pkger version: 0.0.10 and current master (commit bbf47d30725064747140c52b6f36d097354ca487)

</details>
